language: python
sudo: true
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"

env:
  - RL=30
  - RL=31
  - RL=32
  - RL=33
  - RL=34
  - RL=35
  - RL=36

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.8"
    - python: "pypy3"
    - python: "2.7"
    - if: python = 3.4
    - env: RL=30
    - env: RL=31
    - env: RL=32
    - env: RL=33
    - env: RL=34
    - env: RL=36
    - if: python != 3.4
    - env: RL=30
    - env: RL=31
    - env: RL=32
    - env: RL=33
    - env: RL=34
#TEST
before_install:
  - sudo apt-get update
  - sudo apt-get install -y imagemagick
  - sudo apt-get install -y ghostscript
  - sudo sed -i 's#<policy domain="coder" rights="none" pattern="PDF" />#<policy domain="coder" rights="read|write" pattern="PDF" />#' /etc/ImageMagick-6/policy.xml

install:
  - TOX_ENV=py${TRAVIS_PYTHON_VERSION}-rl${RL}
  - pip install tox coveralls Sphinx sphinx-rtd-theme nose

script: tox -e $TOX_ENV
after_success: coveralls $COVERALLS_OPTION

notifications:
  irc: "chat.freenode.net#xhtml2pdf"

before_script:
  - cd doc/source ; sphinx-build -nW -b html -d _build/doctrees . _build/html ; cd ../..
