build: false

environment:
  matrix:
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.6
        RL: 330
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.6
        RL: 340
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.6
        RL: 350
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.6
        RL: 3510
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.6
        RL: 3530
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.6
        RL: 3550
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.6
        RL: 360
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.6
        RL: 365

      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.7
        RL: 330
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.7
        RL: 340
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.7
        RL: 350
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.7
        RL: 3510
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.7
        RL: 3530
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.7
        RL: 3550
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.7
        RL: 360
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.7
        RL: 365

      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.8
        RL: 330
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.8
        RL: 340
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.8
        RL: 350
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.8
        RL: 3510
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.8
        RL: 3530
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.8
        RL: 3550
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.8
        RL: 360
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.8
        RL: 365

      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.9
        RL: 330
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.9
        RL: 340
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.9
        RL: 350
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.9
        RL: 3510
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.9
        RL: 3530
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.9
        RL: 3550
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.9
        RL: 360
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.9
        RL: 365

      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.10
        RL: 330
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.10
        RL: 340
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.10
        RL: 350
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.10
        RL: 3510
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.10
        RL: 3530
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.10
        RL: 3550
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.10
        RL: 360
      - PYTHON_HOME: "C:/Python36"
        PYTHON_VERSION: 3.10
        RL: 365

install:
  - cmd: |
        set TOX_ENV=py%PYTHON_VERSION%-rl%RL%
        echo %TOX_ENV%
        "%PYTHON_HOME%/python.exe" -m pip install --upgrade pip
        "%PYTHON_HOME%/Scripts/pip.exe" install tox coveralls

before_test:
    - cmd: |
        "%PYTHON_HOME%/Scripts/pip.exe" list

# command to run tests
test_script:
  - cmd: |
        %PYTHON_HOME%\Scripts\tox -e %TOX_ENV% -c tox.appveyor.ini
